apiVersion: v1
kind: Service
metadata:
  name: subscription-service
spec:
  type: ClusterIP
  selector:
    app: subscription-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001
